import os

class NetworkFailure(Exception):
  def __init__(self):
    pass
